# Generated by Django 5.2.6 on 2025-09-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fee_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
